using System.Text;
using System.Text.Json;

var repoRoot = FindRepoRoot();
var checkOnly = args.Contains("--check", StringComparer.OrdinalIgnoreCase);
var generator = new Generator(repoRoot);
var result = generator.Run(checkOnly);

if (result.Count == 0)
{
    Console.WriteLine(checkOnly ? "Generated files are current." : "Generated files updated.");
    return 0;
}

foreach (var item in result)
{
    Console.Error.WriteLine(item);
}

return 1;

static string FindRepoRoot()
{
    var current = new DirectoryInfo(AppContext.BaseDirectory);
    while (current is not null)
    {
        if (Directory.Exists(Path.Combine(current.FullName, "src", "canonical")) &&
            Directory.Exists(Path.Combine(current.FullName, "src", "adapters")))
        {
            return current.FullName;
        }

        current = current.Parent;
    }

    throw new InvalidOperationException("Could not locate repository root.");
}

internal sealed class Generator(string repoRoot)
{
    private const string Header = """
        <!--
        Generated from Intent-Driven-Development canonical sources.
        Do not edit this file directly.
        Edit files under src/canonical instead.
        -->

        """;

    public IReadOnlyList<string> Run(bool checkOnly)
    {
        var errors = new List<string>();
        var adaptersRoot = Path.Combine(repoRoot, "src", "adapters");
        foreach (var adapterDir in Directory.GetDirectories(adaptersRoot).OrderBy(Path.GetFileName))
        {
            var adapter = ReadAdapter(adapterDir);
            var expectedFiles = BuildFiles(adapterDir, adapter);
            var outputRoot = Path.Combine(repoRoot, "generated", adapter.Agent);

            if (checkOnly)
            {
                errors.AddRange(CheckFiles(outputRoot, expectedFiles));
                continue;
            }

            Directory.CreateDirectory(outputRoot);
            CleanOutput(outputRoot);
            foreach (var file in expectedFiles)
            {
                var fullPath = Path.Combine(outputRoot, file.RelativePath);
                Directory.CreateDirectory(Path.GetDirectoryName(fullPath)!);
                File.WriteAllText(fullPath, file.Content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            }
        }

        return errors;
    }

    private AdapterConfig ReadAdapter(string adapterDir)
    {
        var json = File.ReadAllText(Path.Combine(adapterDir, "adapter.json"));
        return JsonSerializer.Deserialize<AdapterConfig>(json, new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true
        }) ?? throw new InvalidOperationException($"Invalid adapter config in {adapterDir}.");
    }

    private IReadOnlyList<GeneratedFile> BuildFiles(string adapterDir, AdapterConfig adapter)
    {
        var files = new List<GeneratedFile>();
        var entry = ReadRequired(Path.Combine(adapterDir, "entry.md"));
        var pack = ReadRequired(Path.Combine(repoRoot, "src", "canonical", "packs", "intent-driven-development.md"));
        var methodology = ReadCanonicalMethodology();
        files.Add(new GeneratedFile(adapter.EntryPoint, WithHeader(adapter, JoinBlocks(entry, pack, methodology))));

        if (adapter.SupportsSkills)
        {
            if (string.IsNullOrWhiteSpace(adapter.SkillsRoot))
            {
                throw new InvalidOperationException($"{adapter.Agent} supports skills but has no skillsRoot.");
            }

            var frontMatterPath = Path.Combine(adapterDir, "skill-frontmatter.md");
            var frontMatter = adapter.SupportsFrontMatter ? ReadRequired(frontMatterPath) : "";
            var skillsRoot = Path.Combine(repoRoot, "src", "canonical", "skills");

            foreach (var skillPath in Directory.GetFiles(skillsRoot, "spec-*.md").OrderBy(Path.GetFileName))
            {
                var skillName = Path.GetFileNameWithoutExtension(skillPath);
                var content = ReadRequired(skillPath);
                if (adapter.SupportsFrontMatter)
                {
                    content = JoinBlocks(frontMatter.Replace("{{skillName}}", skillName), content);
                }

                var relativePath = Path.Combine(adapter.SkillsRoot!, skillName, "SKILL.md");
                files.Add(new GeneratedFile(relativePath, WithHeader(adapter, content)));
            }
        }

        files.AddRange(BuildProjectFiles(adapter));
        return files;
    }

    private string ReadCanonicalMethodology()
    {
        var methodologyRoot = Path.Combine(repoRoot, "src", "canonical", "methodology");
        var names = new[]
        {
            "intent-driven-development.md",
            "numbering.md",
            "document-types.md",
            "semantic-changes.md",
            "agent-workflow.md"
        };

        return JoinBlocks(names.Select(name => ReadRequired(Path.Combine(methodologyRoot, name))).ToArray());
    }

    private IReadOnlyList<GeneratedFile> BuildProjectFiles(AdapterConfig adapter)
    {
        var files = new List<GeneratedFile>();
        var specsRoot = Path.Combine(repoRoot, "src", "canonical", "project-files", "specs");
        foreach (var sourcePath in Directory.GetFiles(specsRoot, "*.md", SearchOption.AllDirectories).OrderBy(path => path))
        {
            var relative = Path.GetRelativePath(specsRoot, sourcePath);
            var target = Path.Combine(".specs", relative);
            files.Add(new GeneratedFile(target, WithHeader(adapter, ReadRequired(sourcePath))));
        }

        return files;
    }

    private static IReadOnlyList<string> CheckFiles(string outputRoot, IReadOnlyList<GeneratedFile> expectedFiles)
    {
        var errors = new List<string>();
        var expectedByPath = expectedFiles.ToDictionary(file => Normalize(file.RelativePath), file => file.Content);

        foreach (var expected in expectedByPath)
        {
            var fullPath = Path.Combine(outputRoot, expected.Key);
            if (!File.Exists(fullPath))
            {
                errors.Add($"Missing generated file: {Path.GetRelativePath(Directory.GetCurrentDirectory(), fullPath)}");
                continue;
            }

            var actual = File.ReadAllText(fullPath);
            if (!StringComparer.Ordinal.Equals(actual, expected.Value))
            {
                errors.Add($"Outdated generated file: {Path.GetRelativePath(Directory.GetCurrentDirectory(), fullPath)}");
            }
        }

        if (Directory.Exists(outputRoot))
        {
            foreach (var actualPath in Directory.GetFiles(outputRoot, "*", SearchOption.AllDirectories))
            {
                var relative = Normalize(Path.GetRelativePath(outputRoot, actualPath));
                if (!expectedByPath.ContainsKey(relative))
                {
                    errors.Add($"Unexpected generated file: {Path.GetRelativePath(Directory.GetCurrentDirectory(), actualPath)}");
                }
            }
        }

        return errors;
    }

    private static void CleanOutput(string outputRoot)
    {
        foreach (var entry in Directory.GetFileSystemEntries(outputRoot))
        {
            if (Directory.Exists(entry))
            {
                Directory.Delete(entry, recursive: true);
            }
            else
            {
                File.Delete(entry);
            }
        }
    }

    private static string WithHeader(AdapterConfig adapter, string content) =>
        adapter.GeneratedHeader ? Header + content.TrimEnd() + Environment.NewLine : content.TrimEnd() + Environment.NewLine;

    private static string ReadRequired(string path) =>
        File.Exists(path) ? File.ReadAllText(path) : throw new FileNotFoundException("Required file not found.", path);

    private static string JoinBlocks(params string[] blocks) =>
        string.Join(Environment.NewLine + Environment.NewLine, blocks.Select(block => block.Trim()));

    private static string Normalize(string path) => path.Replace('\\', '/');
}

internal sealed record AdapterConfig(
    string Agent,
    string EntryPoint,
    string? SkillsRoot,
    bool SupportsSkills,
    bool SupportsFrontMatter,
    bool GeneratedHeader);

internal sealed record GeneratedFile(string RelativePath, string Content);
